name: lost_found_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.11.0 <4.0.0' # Fixed the constraint format

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  image_picker: ^1.0.7
  # Real-time Cloud dependencies (Commented out due to build issues)
  # firebase_core: ^3.10.1
  # cloud_firestore: ^5.6.1
  # firebase_storage: ^12.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true